version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data

  graphql-engine:
    image: hasura/graphql-engine:v2.36.0
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydatabase
      HASURA_GRAPHQL_ADMIN_SECRET: "password"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"

  serverless:
    image: node
    working_dir: /serverless
    command: bash -c "npm install -g serverless@3.38.0 && npx serverless offline --host 0.0.0.0"
    volumes:
      - .:/serverless
    ports: ["3000:3000","3002:3002"]

networks:
  project_default:
    driver: bridge
volumes:
  db_data: